<?php
/**
 * $Id$
 *
 * Displays all events from the event log
 */

require_once('find_config.php');
$h->session->requireAdmin();

require('design_admin_head.php');

echo '<h1>Event log</h1>';

if ($session->isSuperAdmin && isset($_GET['events_clearlog'])) {
	$this->query('TRUNCATE tblLogs');
}

$q = 'SELECT COUNT(*) FROM tblLogs WHERE entryLevel <= '.LOGLEVEL_ALL;
$cnt = $db->getOneItem($q);

$pager = makePager($cnt, 15);

$q  = 'SELECT t1.*,t2.userName FROM tblLogs AS t1 ';
$q .= 'LEFT JOIN tblUsers AS t2 ON (t1.userId=t2.userId) ';
$q .= 'WHERE t1.entryLevel <= '.LOGLEVEL_ALL;

if (!empty($_GET['sort']) && $_GET['sort']=='asc') {
	$q .= ' ORDER BY t1.timeCreated ASC,t1.entryId ASC';
	echo 'Showing oldest first - [<a href="'.$_SERVER['PHP_SELF'].'">show newest first</a>]<br/>';
} else {
	$q .= ' ORDER BY t1.timeCreated DESC,t1.entryId DESC';
	echo 'Showing newest first - [<a href="'.$_SERVER['PHP_SELF'].'?sort=asc">show oldest first</a>]<br/>';
}
$q .= $pager['limit'];

$list = $db->getArray($q);
echo $pager['head'];

foreach ($list as $row)
{
	switch ($row['entryLevel']) {
	case LOGLEVEL_NOTICE:  echo '<div class="event_log_notice">'; break;
	case LOGLEVEL_WARNING: echo '<div class="event_log_warning">Warning: '; break;
	case LOGLEVEL_ERROR:   echo '<div class="event_log_error">Error: '; break;
	default: die('Errorx2');
	}

	echo $row['entryText'].'<br/>';
	echo '<i>Generated by <b>';
	if ($row['userId']) echo Users::link($row['userId'], $row['userName']);
	else echo 'Unregistered';
	echo '</b> at '.$row['timeCreated'];

	echo ' from <a href="'.coredev_webroot().'admin/admin_ip.php?ip='.GeoIP_to_IPv4($row['userIP']).'">'.GeoIP_to_IPv4($row['userIP']).'</a>';
	echo '</i></div><br/>';
}

if ($session->isSuperAdmin) echo '<a href="'.$_SERVER['PHP_SELF'].'?events_clearlog">Clear log</a>';

require('design_admin_foot.php');
?>
