<?
	include('include_all.php');

	if (!$_SESSION['isSuperAdmin']) {
		header('Location: '.$config['start_page']);
		die;
	}

	if (isset($_GET['clearlog'])) {
		if (is_numeric($_GET['clearlog'])) {
			clearLogByGeoIP($db, $_GET['clearlog'], LOGLEVEL_ALL);
		} else {
			clearLog($db, LOGLEVEL_ALL);
		}
	}

	$show_geoip = 0;
	if (!empty($_GET['ip']) && is_numeric($_GET['ip'])) $show_geoip = $_GET['ip'];

	include('design_head.php');
	include('design_user_head.php');

		$content = getInfoField($db, 'page_admin_eventlog');
		
		if ($show_geoip) {
			$list = getLogEntriesByGeoIP($db, $show_geoip, LOGLEVEL_ALL);
			$content .= '<h2>Displaying event log entries for IP '.GeoIP_to_IPv4($show_geoip).' only!</h2>';
			$content .= '<a href="'.$_SERVER['PHP_SELF'].'">Show full event log</a><br><br>';
		} else {
			$list = getLogEntries($db, LOGLEVEL_ALL);
		}
		$content .= '<br>'.count($list).' entries in event log<br><br>';
	
		for ($i=0; $i<count($list); $i++) {
			switch ($list[$i]['entryLevel']) {
				case LOGLEVEL_NOTICE:  $content .= 'Notice: '; break; 
				case LOGLEVEL_WARNING: $content .= 'Warning: '; break; 
				case LOGLEVEL_ERROR:   $content .= 'Error: '; break; 
				default: $content .= 'Errorx2: '; break;
			}
			
			$content .= '<b>Entry #'.$list[$i]['entryId'].'</b> - ';
			$content .= $list[$i]['entryText'].'<br>';
			$content .= '<span style="color: #808080;"><i>Generated by <b>';
			if ($list[$i]['userId']) $content .= nameLink($list[$i]['userId'], $list[$i]['userName']);
			else $content .= 'Unregistered';
			$content .= '</b> at '.getDateStringShort($list[$i]['entryTime']);
			
			$ip_v4 = GeoIP_to_IPv4($list[$i]['userIP']);
			$content .= ' from <b><a href="admin_ip.php?ip='.$ip_v4.'">'.$ip_v4.'</a></b> - ';
			
			$content .= getGeoIPCountry($db, $list[$i]['userIP']).', '.getGeoIPCityName($db, $list[$i]['userIP']);
	
			$content .= '</i></span><br>';
			$content .= '<br>';
		}
	
		if ($show_geoip) {
			$content .= '<a href="'.$_SERVER['PHP_SELF'].'?clearlog='.$show_geoip.'">Clear log entries for IP '.GeoIP_to_IPv4($show_geoip).'</a>';
		} else {
			$content .= '<a href="'.$_SERVER['PHP_SELF'].'?clearlog">Clear log</a>';
		}

		echo '<div id="user_admin_content">';
		echo MakeBox('<a href="admin.php">Administrationsgr&auml;nssnitt</a>|Event log', $content);
		echo '</div>';

	include('design_admin_foot.php');
	include('design_foot.php');
?>