<?
	/*
		WARNING! DO NOT EDIT THIS FILE!
		
		These settings are DEFAULT SETTINGS.
		Edit config.php to overwrite default settings.
	*/


	$config['path_functions'] = '../site_functions/';


	/* Include config.php with localized configuration settings */
	include_once('config.php');
	
	//$config['path_functions'] may be overwritten in config.php
	if (!is_dir($config['path_functions'])) die('<b>FATAL ERROR: '.$config['path_functions'].' dont exists!</b>');

	/* Include locales files */
	include_once($config['path_functions'].'locales_standard.php');
	include_once($config['path_functions'].'locales_time.php');
	include_once($config['path_functions'].'locales_forum.php');

	$config['forum']['text'] = $config['forum']['text'][ $config['language'] ];		//language for forum module
	$config['time'] = $config['time'][ $config['language'] ];		//language for time module
	$config['text'] = $config['text'][ $config['language'] ];		//language for default text strings

	/* Include functions files */
	include_once($config['path_functions'].'functions_log.php');
	include_once($config['path_functions'].'functions_db.php');
	include_once($config['path_functions'].'functions_user.php');
	include_once($config['path_functions'].'functions_time.php');
	include_once($config['path_functions'].'functions_dictionary.php');
	include_once($config['path_functions'].'functions_geoip.php');
	include_once($config['path_functions'].'functions_files.php');
	include_once($config['path_functions'].'functions_forums.php');
	include_once($config['path_functions'].'functions_misc.php');
	include_once($config['path_functions'].'functions_infofields.php');
	include_once($config['path_functions'].'functions_comments.php');
	include_once($config['path_functions'].'functions_settings.php');
	include_once($config['path_functions'].'functions_session.php');
	include_once($config['path_functions'].'functions_todo.php');
	include_once($config['path_functions'].'functions_timedsubscriptions.php');
	include_once($config['path_functions'].'functions_accessgroups.php');
	include_once($config['path_functions'].'functions_subscriptions.php');
	include_once($config['path_functions'].'functions_search.php');
	include_once($config['path_functions'].'functions_moderation.php');
	include_once($config['path_functions'].'functions_userdata.php');
	include_once($config['path_functions'].'functions_news.php');
	include_once($config['path_functions'].'functions_guestbook.php');
	include_once($config['path_functions'].'functions_quicklists.php');
	include_once($config['path_functions'].'functions_messages.php');
	include_once($config['path_functions'].'functions_articles.php');
	include_once($config['path_functions'].'functions_estore.php');
	include_once($config['path_functions'].'functions_matchmaking.php');
	include_once($config['path_functions'].'functions_polls.php');
	include_once($config['path_functions'].'functions_blogs.php');
	include_once($config['path_functions'].'functions_categories.php');
	include_once($config['path_functions'].'functions_favoritegames.php');
	include_once($config['path_functions'].'functions_dns_cache.php');


	//$config['database_1'] must be specified in config.php
	$db = dbOpen($config['database_1']);
	
	if (!empty($config['database_geoip'])) {
		$geodb = dbOpen($config['database_geoip']);
	}
?>